version: "3"
services:
    go:
        build: ./
        command: /bin/sh -c "go run ."
        stdin_open: true
        tty: true
        volumes:
            - .:/app
        ports:
            - "8081:${APP_PORT}"